[package]
name = "obsidian_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
log = "0.4.11"
winit = "0.24.0"
simplelog = {version = "0.9.0", features = ["termcolor"]}